[env]
TERM = "alacritty"

[font]
size = 8.0

[font.bold]
family = "monospace"

[font.italic]
family = "monospace"

[font.normal]
family = "monospace"

[scrolling]
history = 10000
multiplier = 3

[window]
title = "Alacritty"
