#!/bin/sh
##=============================================================================
## my aliasrc for macOS
##=============================================================================

## Colorize commands when possible.
alias \
	ll="ls -lahG" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
    rm="rm -i" \
    cp="cp -i" \
    mv="mv -i"

## run mutt from attachments directory for save attachments in it
alias mutt='cd ~/attachments && mutt'
